// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Side int32

const (
	Side_Ask Side = 0
	Side_Bid Side = 1
)

var Side_name = map[int32]string{
	0: "Ask",
	1: "Bid",
}

var Side_value = map[string]int32{
	"Ask": 0,
	"Bid": 1,
}

func (x Side) String() string {
	return proto.EnumName(Side_name, int32(x))
}

func (Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

type Strategy int32

const (
	Strategy_Market Strategy = 0
	Strategy_Limit  Strategy = 1
	Strategy_Follow Strategy = 2
	Strategy_Flex   Strategy = 3
)

var Strategy_name = map[int32]string{
	0: "Market",
	1: "Limit",
	2: "Follow",
	3: "Flex",
}

var Strategy_value = map[string]int32{
	"Market": 0,
	"Limit":  1,
	"Follow": 2,
	"Flex":   3,
}

func (x Strategy) String() string {
	return proto.EnumName(Strategy_name, int32(x))
}

func (Strategy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

type SortOrder int32

const (
	SortOrder_DESC SortOrder = 0
	SortOrder_ASC  SortOrder = 1
)

var SortOrder_name = map[int32]string{
	0: "DESC",
	1: "ASC",
}

var SortOrder_value = map[string]int32{
	"DESC": 0,
	"ASC":  1,
}

func (x SortOrder) String() string {
	return proto.EnumName(SortOrder_name, int32(x))
}

func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

type Pair_State int32

const (
	Pair_Trading Pair_State = 0
	Pair_Break   Pair_State = 1
)

var Pair_State_name = map[int32]string{
	0: "Trading",
	1: "Break",
}

var Pair_State_value = map[string]int32{
	"Trading": 0,
	"Break":   1,
}

func (x Pair_State) String() string {
	return proto.EnumName(Pair_State_name, int32(x))
}

func (Pair_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3, 0}
}

type Book_State int32

const (
	Book_Pending Book_State = 0
	Book_Paid    Book_State = 1
	Book_Done    Book_State = 2
)

var Book_State_name = map[int32]string{
	0: "Pending",
	1: "Paid",
	2: "Done",
}

var Book_State_value = map[string]int32{
	"Pending": 0,
	"Paid":    1,
	"Done":    2,
}

func (x Book_State) String() string {
	return proto.EnumName(Book_State_name, int32(x))
}

func (Book_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4, 0}
}

type Order_State int32

const (
	Order_Trading   Order_State = 0
	Order_Filled    Order_State = 1
	Order_Cancelled Order_State = 2
	Order_Rejected  Order_State = 3
	Order_Timeout   Order_State = 4
)

var Order_State_name = map[int32]string{
	0: "Trading",
	1: "Filled",
	2: "Cancelled",
	3: "Rejected",
	4: "Timeout",
}

var Order_State_value = map[string]int32{
	"Trading":   0,
	"Filled":    1,
	"Cancelled": 2,
	"Rejected":  3,
	"Timeout":   4,
}

func (x Order_State) String() string {
	return proto.EnumName(Order_State_name, int32(x))
}

func (Order_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5, 0}
}

type Pagination struct {
	NextCursor           string   `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasNext              bool     `protobuf:"varint,2,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetNextCursor() string {
	if m != nil {
		return m.NextCursor
	}
	return ""
}

func (m *Pagination) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

type Depth struct {
	Version              string               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Asks                 []*Depth_Order       `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids                 []*Depth_Order       `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Depth) Reset()         { *m = Depth{} }
func (m *Depth) String() string { return proto.CompactTextString(m) }
func (*Depth) ProtoMessage()    {}
func (*Depth) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Depth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Depth.Unmarshal(m, b)
}
func (m *Depth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Depth.Marshal(b, m, deterministic)
}
func (m *Depth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Depth.Merge(m, src)
}
func (m *Depth) XXX_Size() int {
	return xxx_messageInfo_Depth.Size(m)
}
func (m *Depth) XXX_DiscardUnknown() {
	xxx_messageInfo_Depth.DiscardUnknown(m)
}

var xxx_messageInfo_Depth proto.InternalMessageInfo

func (m *Depth) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Depth) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Depth) GetAsks() []*Depth_Order {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *Depth) GetBids() []*Depth_Order {
	if m != nil {
		return m.Bids
	}
	return nil
}

type Depth_Order struct {
	Price                string   `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Depth_Order) Reset()         { *m = Depth_Order{} }
func (m *Depth_Order) String() string { return proto.CompactTextString(m) }
func (*Depth_Order) ProtoMessage()    {}
func (*Depth_Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1, 0}
}

func (m *Depth_Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Depth_Order.Unmarshal(m, b)
}
func (m *Depth_Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Depth_Order.Marshal(b, m, deterministic)
}
func (m *Depth_Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Depth_Order.Merge(m, src)
}
func (m *Depth_Order) XXX_Size() int {
	return xxx_messageInfo_Depth_Order.Size(m)
}
func (m *Depth_Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Depth_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Depth_Order proto.InternalMessageInfo

func (m *Depth_Order) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Depth_Order) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type Asset struct {
	AssetId   string `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Symbol    string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Logo      string `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Precision int32  `protobuf:"varint,5,opt,name=precision,proto3" json:"precision,omitempty"`
	// 最小下单量
	Min string `protobuf:"bytes,6,opt,name=min,proto3" json:"min,omitempty"`
	// 最大下单量
	Max                  string   `protobuf:"bytes,7,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *Asset) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Asset) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *Asset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Asset) GetPrecision() int32 {
	if m != nil {
		return m.Precision
	}
	return 0
}

func (m *Asset) GetMin() string {
	if m != nil {
		return m.Min
	}
	return ""
}

func (m *Asset) GetMax() string {
	if m != nil {
		return m.Max
	}
	return ""
}

type Pair struct {
	Symbol         string     `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	DisplaySymbol  string     `protobuf:"bytes,2,opt,name=display_symbol,json=displaySymbol,proto3" json:"display_symbol,omitempty"`
	Exchange       string     `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	State          Pair_State `protobuf:"varint,4,opt,name=state,proto3,enum=fox.atm.service.Pair_State" json:"state,omitempty"`
	PricePrecision int32      `protobuf:"varint,5,opt,name=price_precision,json=pricePrecision,proto3" json:"price_precision,omitempty"`
	BasePrecision  int32      `protobuf:"varint,6,opt,name=base_precision,json=basePrecision,proto3" json:"base_precision,omitempty"`
	QuotePrecision int32      `protobuf:"varint,7,opt,name=quote_precision,json=quotePrecision,proto3" json:"quote_precision,omitempty"`
	// 24h 价格变化幅度
	Change string `protobuf:"bytes,8,opt,name=change,proto3" json:"change,omitempty"`
	// 当前价格
	Price string `protobuf:"bytes,9,opt,name=price,proto3" json:"price,omitempty"`
	// 买一价格
	PriceBuy string `protobuf:"bytes,10,opt,name=price_buy,json=priceBuy,proto3" json:"price_buy,omitempty"`
	// 卖一价格
	PriceSell            string   `protobuf:"bytes,11,opt,name=price_sell,json=priceSell,proto3" json:"price_sell,omitempty"`
	Strategies           []string `protobuf:"bytes,12,rep,name=strategies,proto3" json:"strategies,omitempty"`
	Base                 *Asset   `protobuf:"bytes,13,opt,name=base,proto3" json:"base,omitempty"`
	Quote                *Asset   `protobuf:"bytes,14,opt,name=quote,proto3" json:"quote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (m *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(m, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Pair) GetDisplaySymbol() string {
	if m != nil {
		return m.DisplaySymbol
	}
	return ""
}

func (m *Pair) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Pair) GetState() Pair_State {
	if m != nil {
		return m.State
	}
	return Pair_Trading
}

func (m *Pair) GetPricePrecision() int32 {
	if m != nil {
		return m.PricePrecision
	}
	return 0
}

func (m *Pair) GetBasePrecision() int32 {
	if m != nil {
		return m.BasePrecision
	}
	return 0
}

func (m *Pair) GetQuotePrecision() int32 {
	if m != nil {
		return m.QuotePrecision
	}
	return 0
}

func (m *Pair) GetChange() string {
	if m != nil {
		return m.Change
	}
	return ""
}

func (m *Pair) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Pair) GetPriceBuy() string {
	if m != nil {
		return m.PriceBuy
	}
	return ""
}

func (m *Pair) GetPriceSell() string {
	if m != nil {
		return m.PriceSell
	}
	return ""
}

func (m *Pair) GetStrategies() []string {
	if m != nil {
		return m.Strategies
	}
	return nil
}

func (m *Pair) GetBase() *Asset {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *Pair) GetQuote() *Asset {
	if m != nil {
		return m.Quote
	}
	return nil
}

type Book struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	State                Book_State           `protobuf:"varint,3,opt,name=state,proto3,enum=fox.atm.service.Book_State" json:"state,omitempty"`
	MerchantId           string               `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	BrokerId             string               `protobuf:"bytes,5,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	TraceId              string               `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	UserId               string               `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Payer                string               `protobuf:"bytes,8,opt,name=payer,proto3" json:"payer,omitempty"`
	SnapshotId           string               `protobuf:"bytes,9,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	ReceiptId            string               `protobuf:"bytes,10,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	Memo                 string               `protobuf:"bytes,11,opt,name=memo,proto3" json:"memo,omitempty"`
	Funds                string               `protobuf:"bytes,12,opt,name=funds,proto3" json:"funds,omitempty"`
	PaySymbol            string               `protobuf:"bytes,13,opt,name=pay_symbol,json=paySymbol,proto3" json:"pay_symbol,omitempty"`
	FillSymbol           string               `protobuf:"bytes,14,opt,name=fill_symbol,json=fillSymbol,proto3" json:"fill_symbol,omitempty"`
	Strategy             Strategy             `protobuf:"varint,15,opt,name=strategy,proto3,enum=fox.atm.service.Strategy" json:"strategy,omitempty"`
	Price                string               `protobuf:"bytes,16,opt,name=price,proto3" json:"price,omitempty"`
	Discount             string               `protobuf:"bytes,17,opt,name=discount,proto3" json:"discount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Book) GetState() Book_State {
	if m != nil {
		return m.State
	}
	return Book_Pending
}

func (m *Book) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *Book) GetBrokerId() string {
	if m != nil {
		return m.BrokerId
	}
	return ""
}

func (m *Book) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Book) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Book) GetPayer() string {
	if m != nil {
		return m.Payer
	}
	return ""
}

func (m *Book) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

func (m *Book) GetReceiptId() string {
	if m != nil {
		return m.ReceiptId
	}
	return ""
}

func (m *Book) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *Book) GetFunds() string {
	if m != nil {
		return m.Funds
	}
	return ""
}

func (m *Book) GetPaySymbol() string {
	if m != nil {
		return m.PaySymbol
	}
	return ""
}

func (m *Book) GetFillSymbol() string {
	if m != nil {
		return m.FillSymbol
	}
	return ""
}

func (m *Book) GetStrategy() Strategy {
	if m != nil {
		return m.Strategy
	}
	return Strategy_Market
}

func (m *Book) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Book) GetDiscount() string {
	if m != nil {
		return m.Discount
	}
	return ""
}

type Order struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CancelledAt          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	UserId               string               `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId           string               `protobuf:"bytes,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	State                Order_State          `protobuf:"varint,7,opt,name=state,proto3,enum=fox.atm.service.Order_State" json:"state,omitempty"`
	PaySymbol            string               `protobuf:"bytes,8,opt,name=pay_symbol,json=paySymbol,proto3" json:"pay_symbol,omitempty"`
	FillSymbol           string               `protobuf:"bytes,9,opt,name=fill_symbol,json=fillSymbol,proto3" json:"fill_symbol,omitempty"`
	Symbol               string               `protobuf:"bytes,10,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side                 Side                 `protobuf:"varint,11,opt,name=side,proto3,enum=fox.atm.service.Side" json:"side,omitempty"`
	Strategy             Strategy             `protobuf:"varint,12,opt,name=strategy,proto3,enum=fox.atm.service.Strategy" json:"strategy,omitempty"`
	Price                string               `protobuf:"bytes,13,opt,name=price,proto3" json:"price,omitempty"`
	Discount             string               `protobuf:"bytes,14,opt,name=discount,proto3" json:"discount,omitempty"`
	Funds                string               `protobuf:"bytes,15,opt,name=funds,proto3" json:"funds,omitempty"`
	FilledFunds          string               `protobuf:"bytes,16,opt,name=filled_funds,json=filledFunds,proto3" json:"filled_funds,omitempty"`
	FilledAmount         string               `protobuf:"bytes,17,opt,name=filled_amount,json=filledAmount,proto3" json:"filled_amount,omitempty"`
	ExtraFilledAmount    string               `protobuf:"bytes,18,opt,name=extra_filled_amount,json=extraFilledAmount,proto3" json:"extra_filled_amount,omitempty"`
	FeeAmount            string               `protobuf:"bytes,19,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	AveragePrice         string               `protobuf:"bytes,20,opt,name=average_price,json=averagePrice,proto3" json:"average_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Order) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Order) GetCancelledAt() *timestamp.Timestamp {
	if m != nil {
		return m.CancelledAt
	}
	return nil
}

func (m *Order) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Order) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *Order) GetState() Order_State {
	if m != nil {
		return m.State
	}
	return Order_Trading
}

func (m *Order) GetPaySymbol() string {
	if m != nil {
		return m.PaySymbol
	}
	return ""
}

func (m *Order) GetFillSymbol() string {
	if m != nil {
		return m.FillSymbol
	}
	return ""
}

func (m *Order) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Order) GetSide() Side {
	if m != nil {
		return m.Side
	}
	return Side_Ask
}

func (m *Order) GetStrategy() Strategy {
	if m != nil {
		return m.Strategy
	}
	return Strategy_Market
}

func (m *Order) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Order) GetDiscount() string {
	if m != nil {
		return m.Discount
	}
	return ""
}

func (m *Order) GetFunds() string {
	if m != nil {
		return m.Funds
	}
	return ""
}

func (m *Order) GetFilledFunds() string {
	if m != nil {
		return m.FilledFunds
	}
	return ""
}

func (m *Order) GetFilledAmount() string {
	if m != nil {
		return m.FilledAmount
	}
	return ""
}

func (m *Order) GetExtraFilledAmount() string {
	if m != nil {
		return m.ExtraFilledAmount
	}
	return ""
}

func (m *Order) GetFeeAmount() string {
	if m != nil {
		return m.FeeAmount
	}
	return ""
}

func (m *Order) GetAveragePrice() string {
	if m != nil {
		return m.AveragePrice
	}
	return ""
}

type OrderReport struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Date                 string               `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	UserId               string               `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId           string               `protobuf:"bytes,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Symbol               string               `protobuf:"bytes,6,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side                 string               `protobuf:"bytes,7,opt,name=side,proto3" json:"side,omitempty"`
	FilledAmount         string               `protobuf:"bytes,8,opt,name=filled_amount,json=filledAmount,proto3" json:"filled_amount,omitempty"`
	ObtainedAmount       string               `protobuf:"bytes,9,opt,name=obtained_amount,json=obtainedAmount,proto3" json:"obtained_amount,omitempty"`
	FeeAmount            string               `protobuf:"bytes,10,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	FeeAsset             string               `protobuf:"bytes,11,opt,name=fee_asset,json=feeAsset,proto3" json:"fee_asset,omitempty"`
	Count                int32                `protobuf:"varint,12,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderReport) Reset()         { *m = OrderReport{} }
func (m *OrderReport) String() string { return proto.CompactTextString(m) }
func (*OrderReport) ProtoMessage()    {}
func (*OrderReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *OrderReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderReport.Unmarshal(m, b)
}
func (m *OrderReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderReport.Marshal(b, m, deterministic)
}
func (m *OrderReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderReport.Merge(m, src)
}
func (m *OrderReport) XXX_Size() int {
	return xxx_messageInfo_OrderReport.Size(m)
}
func (m *OrderReport) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderReport.DiscardUnknown(m)
}

var xxx_messageInfo_OrderReport proto.InternalMessageInfo

func (m *OrderReport) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderReport) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *OrderReport) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *OrderReport) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OrderReport) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *OrderReport) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderReport) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *OrderReport) GetFilledAmount() string {
	if m != nil {
		return m.FilledAmount
	}
	return ""
}

func (m *OrderReport) GetObtainedAmount() string {
	if m != nil {
		return m.ObtainedAmount
	}
	return ""
}

func (m *OrderReport) GetFeeAmount() string {
	if m != nil {
		return m.FeeAmount
	}
	return ""
}

func (m *OrderReport) GetFeeAsset() string {
	if m != nil {
		return m.FeeAsset
	}
	return ""
}

func (m *OrderReport) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	BrokerId             string   `protobuf:"bytes,4,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetBrokerId() string {
	if m != nil {
		return m.BrokerId
	}
	return ""
}

type MarketServiceReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketServiceReq) Reset()         { *m = MarketServiceReq{} }
func (m *MarketServiceReq) String() string { return proto.CompactTextString(m) }
func (*MarketServiceReq) ProtoMessage()    {}
func (*MarketServiceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *MarketServiceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketServiceReq.Unmarshal(m, b)
}
func (m *MarketServiceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketServiceReq.Marshal(b, m, deterministic)
}
func (m *MarketServiceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketServiceReq.Merge(m, src)
}
func (m *MarketServiceReq) XXX_Size() int {
	return xxx_messageInfo_MarketServiceReq.Size(m)
}
func (m *MarketServiceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketServiceReq.DiscardUnknown(m)
}

var xxx_messageInfo_MarketServiceReq proto.InternalMessageInfo

type MarketServiceReq_ListPairs struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketServiceReq_ListPairs) Reset()         { *m = MarketServiceReq_ListPairs{} }
func (m *MarketServiceReq_ListPairs) String() string { return proto.CompactTextString(m) }
func (*MarketServiceReq_ListPairs) ProtoMessage()    {}
func (*MarketServiceReq_ListPairs) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8, 0}
}

func (m *MarketServiceReq_ListPairs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketServiceReq_ListPairs.Unmarshal(m, b)
}
func (m *MarketServiceReq_ListPairs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketServiceReq_ListPairs.Marshal(b, m, deterministic)
}
func (m *MarketServiceReq_ListPairs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketServiceReq_ListPairs.Merge(m, src)
}
func (m *MarketServiceReq_ListPairs) XXX_Size() int {
	return xxx_messageInfo_MarketServiceReq_ListPairs.Size(m)
}
func (m *MarketServiceReq_ListPairs) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketServiceReq_ListPairs.DiscardUnknown(m)
}

var xxx_messageInfo_MarketServiceReq_ListPairs proto.InternalMessageInfo

type MarketServiceReq_ReadPair struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketServiceReq_ReadPair) Reset()         { *m = MarketServiceReq_ReadPair{} }
func (m *MarketServiceReq_ReadPair) String() string { return proto.CompactTextString(m) }
func (*MarketServiceReq_ReadPair) ProtoMessage()    {}
func (*MarketServiceReq_ReadPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8, 1}
}

func (m *MarketServiceReq_ReadPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketServiceReq_ReadPair.Unmarshal(m, b)
}
func (m *MarketServiceReq_ReadPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketServiceReq_ReadPair.Marshal(b, m, deterministic)
}
func (m *MarketServiceReq_ReadPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketServiceReq_ReadPair.Merge(m, src)
}
func (m *MarketServiceReq_ReadPair) XXX_Size() int {
	return xxx_messageInfo_MarketServiceReq_ReadPair.Size(m)
}
func (m *MarketServiceReq_ReadPair) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketServiceReq_ReadPair.DiscardUnknown(m)
}

var xxx_messageInfo_MarketServiceReq_ReadPair proto.InternalMessageInfo

func (m *MarketServiceReq_ReadPair) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type MarketServiceReq_ReadDepth struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketServiceReq_ReadDepth) Reset()         { *m = MarketServiceReq_ReadDepth{} }
func (m *MarketServiceReq_ReadDepth) String() string { return proto.CompactTextString(m) }
func (*MarketServiceReq_ReadDepth) ProtoMessage()    {}
func (*MarketServiceReq_ReadDepth) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8, 2}
}

func (m *MarketServiceReq_ReadDepth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketServiceReq_ReadDepth.Unmarshal(m, b)
}
func (m *MarketServiceReq_ReadDepth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketServiceReq_ReadDepth.Marshal(b, m, deterministic)
}
func (m *MarketServiceReq_ReadDepth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketServiceReq_ReadDepth.Merge(m, src)
}
func (m *MarketServiceReq_ReadDepth) XXX_Size() int {
	return xxx_messageInfo_MarketServiceReq_ReadDepth.Size(m)
}
func (m *MarketServiceReq_ReadDepth) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketServiceReq_ReadDepth.DiscardUnknown(m)
}

var xxx_messageInfo_MarketServiceReq_ReadDepth proto.InternalMessageInfo

func (m *MarketServiceReq_ReadDepth) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type MarketServiceResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketServiceResp) Reset()         { *m = MarketServiceResp{} }
func (m *MarketServiceResp) String() string { return proto.CompactTextString(m) }
func (*MarketServiceResp) ProtoMessage()    {}
func (*MarketServiceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *MarketServiceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketServiceResp.Unmarshal(m, b)
}
func (m *MarketServiceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketServiceResp.Marshal(b, m, deterministic)
}
func (m *MarketServiceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketServiceResp.Merge(m, src)
}
func (m *MarketServiceResp) XXX_Size() int {
	return xxx_messageInfo_MarketServiceResp.Size(m)
}
func (m *MarketServiceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketServiceResp.DiscardUnknown(m)
}

var xxx_messageInfo_MarketServiceResp proto.InternalMessageInfo

type MarketServiceResp_ListPairs struct {
	Pairs                []*Pair  `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketServiceResp_ListPairs) Reset()         { *m = MarketServiceResp_ListPairs{} }
func (m *MarketServiceResp_ListPairs) String() string { return proto.CompactTextString(m) }
func (*MarketServiceResp_ListPairs) ProtoMessage()    {}
func (*MarketServiceResp_ListPairs) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9, 0}
}

func (m *MarketServiceResp_ListPairs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketServiceResp_ListPairs.Unmarshal(m, b)
}
func (m *MarketServiceResp_ListPairs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketServiceResp_ListPairs.Marshal(b, m, deterministic)
}
func (m *MarketServiceResp_ListPairs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketServiceResp_ListPairs.Merge(m, src)
}
func (m *MarketServiceResp_ListPairs) XXX_Size() int {
	return xxx_messageInfo_MarketServiceResp_ListPairs.Size(m)
}
func (m *MarketServiceResp_ListPairs) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketServiceResp_ListPairs.DiscardUnknown(m)
}

var xxx_messageInfo_MarketServiceResp_ListPairs proto.InternalMessageInfo

func (m *MarketServiceResp_ListPairs) GetPairs() []*Pair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type UserServiceReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserServiceReq) Reset()         { *m = UserServiceReq{} }
func (m *UserServiceReq) String() string { return proto.CompactTextString(m) }
func (*UserServiceReq) ProtoMessage()    {}
func (*UserServiceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *UserServiceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserServiceReq.Unmarshal(m, b)
}
func (m *UserServiceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserServiceReq.Marshal(b, m, deterministic)
}
func (m *UserServiceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserServiceReq.Merge(m, src)
}
func (m *UserServiceReq) XXX_Size() int {
	return xxx_messageInfo_UserServiceReq.Size(m)
}
func (m *UserServiceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserServiceReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserServiceReq proto.InternalMessageInfo

type UserServiceReq_Me struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserServiceReq_Me) Reset()         { *m = UserServiceReq_Me{} }
func (m *UserServiceReq_Me) String() string { return proto.CompactTextString(m) }
func (*UserServiceReq_Me) ProtoMessage()    {}
func (*UserServiceReq_Me) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10, 0}
}

func (m *UserServiceReq_Me) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserServiceReq_Me.Unmarshal(m, b)
}
func (m *UserServiceReq_Me) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserServiceReq_Me.Marshal(b, m, deterministic)
}
func (m *UserServiceReq_Me) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserServiceReq_Me.Merge(m, src)
}
func (m *UserServiceReq_Me) XXX_Size() int {
	return xxx_messageInfo_UserServiceReq_Me.Size(m)
}
func (m *UserServiceReq_Me) XXX_DiscardUnknown() {
	xxx_messageInfo_UserServiceReq_Me.DiscardUnknown(m)
}

var xxx_messageInfo_UserServiceReq_Me proto.InternalMessageInfo

type UserServiceReq_ReadOrder struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserServiceReq_ReadOrder) Reset()         { *m = UserServiceReq_ReadOrder{} }
func (m *UserServiceReq_ReadOrder) String() string { return proto.CompactTextString(m) }
func (*UserServiceReq_ReadOrder) ProtoMessage()    {}
func (*UserServiceReq_ReadOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10, 1}
}

func (m *UserServiceReq_ReadOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserServiceReq_ReadOrder.Unmarshal(m, b)
}
func (m *UserServiceReq_ReadOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserServiceReq_ReadOrder.Marshal(b, m, deterministic)
}
func (m *UserServiceReq_ReadOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserServiceReq_ReadOrder.Merge(m, src)
}
func (m *UserServiceReq_ReadOrder) XXX_Size() int {
	return xxx_messageInfo_UserServiceReq_ReadOrder.Size(m)
}
func (m *UserServiceReq_ReadOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_UserServiceReq_ReadOrder.DiscardUnknown(m)
}

var xxx_messageInfo_UserServiceReq_ReadOrder proto.InternalMessageInfo

func (m *UserServiceReq_ReadOrder) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

type UserServiceReq_ListOrders struct {
	Symbol               string    `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side                 string    `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`
	Strategy             string    `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	State                string    `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	MerchantId           string    `protobuf:"bytes,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Order                SortOrder `protobuf:"varint,6,opt,name=order,proto3,enum=fox.atm.service.SortOrder" json:"order,omitempty"`
	Cursor               string    `protobuf:"bytes,7,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit                int64     `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserServiceReq_ListOrders) Reset()         { *m = UserServiceReq_ListOrders{} }
func (m *UserServiceReq_ListOrders) String() string { return proto.CompactTextString(m) }
func (*UserServiceReq_ListOrders) ProtoMessage()    {}
func (*UserServiceReq_ListOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10, 2}
}

func (m *UserServiceReq_ListOrders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserServiceReq_ListOrders.Unmarshal(m, b)
}
func (m *UserServiceReq_ListOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserServiceReq_ListOrders.Marshal(b, m, deterministic)
}
func (m *UserServiceReq_ListOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserServiceReq_ListOrders.Merge(m, src)
}
func (m *UserServiceReq_ListOrders) XXX_Size() int {
	return xxx_messageInfo_UserServiceReq_ListOrders.Size(m)
}
func (m *UserServiceReq_ListOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_UserServiceReq_ListOrders.DiscardUnknown(m)
}

var xxx_messageInfo_UserServiceReq_ListOrders proto.InternalMessageInfo

func (m *UserServiceReq_ListOrders) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *UserServiceReq_ListOrders) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *UserServiceReq_ListOrders) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *UserServiceReq_ListOrders) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *UserServiceReq_ListOrders) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *UserServiceReq_ListOrders) GetOrder() SortOrder {
	if m != nil {
		return m.Order
	}
	return SortOrder_DESC
}

func (m *UserServiceReq_ListOrders) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *UserServiceReq_ListOrders) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type UserServiceReq_CancelOrder struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserServiceReq_CancelOrder) Reset()         { *m = UserServiceReq_CancelOrder{} }
func (m *UserServiceReq_CancelOrder) String() string { return proto.CompactTextString(m) }
func (*UserServiceReq_CancelOrder) ProtoMessage()    {}
func (*UserServiceReq_CancelOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10, 3}
}

func (m *UserServiceReq_CancelOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserServiceReq_CancelOrder.Unmarshal(m, b)
}
func (m *UserServiceReq_CancelOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserServiceReq_CancelOrder.Marshal(b, m, deterministic)
}
func (m *UserServiceReq_CancelOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserServiceReq_CancelOrder.Merge(m, src)
}
func (m *UserServiceReq_CancelOrder) XXX_Size() int {
	return xxx_messageInfo_UserServiceReq_CancelOrder.Size(m)
}
func (m *UserServiceReq_CancelOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_UserServiceReq_CancelOrder.DiscardUnknown(m)
}

var xxx_messageInfo_UserServiceReq_CancelOrder proto.InternalMessageInfo

func (m *UserServiceReq_CancelOrder) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

type UserServiceResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserServiceResp) Reset()         { *m = UserServiceResp{} }
func (m *UserServiceResp) String() string { return proto.CompactTextString(m) }
func (*UserServiceResp) ProtoMessage()    {}
func (*UserServiceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *UserServiceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserServiceResp.Unmarshal(m, b)
}
func (m *UserServiceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserServiceResp.Marshal(b, m, deterministic)
}
func (m *UserServiceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserServiceResp.Merge(m, src)
}
func (m *UserServiceResp) XXX_Size() int {
	return xxx_messageInfo_UserServiceResp.Size(m)
}
func (m *UserServiceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserServiceResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserServiceResp proto.InternalMessageInfo

type UserServiceResp_CancelOrder struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserServiceResp_CancelOrder) Reset()         { *m = UserServiceResp_CancelOrder{} }
func (m *UserServiceResp_CancelOrder) String() string { return proto.CompactTextString(m) }
func (*UserServiceResp_CancelOrder) ProtoMessage()    {}
func (*UserServiceResp_CancelOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11, 0}
}

func (m *UserServiceResp_CancelOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserServiceResp_CancelOrder.Unmarshal(m, b)
}
func (m *UserServiceResp_CancelOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserServiceResp_CancelOrder.Marshal(b, m, deterministic)
}
func (m *UserServiceResp_CancelOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserServiceResp_CancelOrder.Merge(m, src)
}
func (m *UserServiceResp_CancelOrder) XXX_Size() int {
	return xxx_messageInfo_UserServiceResp_CancelOrder.Size(m)
}
func (m *UserServiceResp_CancelOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_UserServiceResp_CancelOrder.DiscardUnknown(m)
}

var xxx_messageInfo_UserServiceResp_CancelOrder proto.InternalMessageInfo

type UserServiceResp_ListOrders struct {
	Orders               []*Order    `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Pagination           *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserServiceResp_ListOrders) Reset()         { *m = UserServiceResp_ListOrders{} }
func (m *UserServiceResp_ListOrders) String() string { return proto.CompactTextString(m) }
func (*UserServiceResp_ListOrders) ProtoMessage()    {}
func (*UserServiceResp_ListOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11, 1}
}

func (m *UserServiceResp_ListOrders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserServiceResp_ListOrders.Unmarshal(m, b)
}
func (m *UserServiceResp_ListOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserServiceResp_ListOrders.Marshal(b, m, deterministic)
}
func (m *UserServiceResp_ListOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserServiceResp_ListOrders.Merge(m, src)
}
func (m *UserServiceResp_ListOrders) XXX_Size() int {
	return xxx_messageInfo_UserServiceResp_ListOrders.Size(m)
}
func (m *UserServiceResp_ListOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_UserServiceResp_ListOrders.DiscardUnknown(m)
}

var xxx_messageInfo_UserServiceResp_ListOrders proto.InternalMessageInfo

func (m *UserServiceResp_ListOrders) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *UserServiceResp_ListOrders) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type MerchantServiceReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantServiceReq) Reset()         { *m = MerchantServiceReq{} }
func (m *MerchantServiceReq) String() string { return proto.CompactTextString(m) }
func (*MerchantServiceReq) ProtoMessage()    {}
func (*MerchantServiceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *MerchantServiceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantServiceReq.Unmarshal(m, b)
}
func (m *MerchantServiceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantServiceReq.Marshal(b, m, deterministic)
}
func (m *MerchantServiceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantServiceReq.Merge(m, src)
}
func (m *MerchantServiceReq) XXX_Size() int {
	return xxx_messageInfo_MerchantServiceReq.Size(m)
}
func (m *MerchantServiceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantServiceReq.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantServiceReq proto.InternalMessageInfo

type MerchantServiceReq_CreateBook struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReceiptId            string   `protobuf:"bytes,3,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantServiceReq_CreateBook) Reset()         { *m = MerchantServiceReq_CreateBook{} }
func (m *MerchantServiceReq_CreateBook) String() string { return proto.CompactTextString(m) }
func (*MerchantServiceReq_CreateBook) ProtoMessage()    {}
func (*MerchantServiceReq_CreateBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12, 0}
}

func (m *MerchantServiceReq_CreateBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantServiceReq_CreateBook.Unmarshal(m, b)
}
func (m *MerchantServiceReq_CreateBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantServiceReq_CreateBook.Marshal(b, m, deterministic)
}
func (m *MerchantServiceReq_CreateBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantServiceReq_CreateBook.Merge(m, src)
}
func (m *MerchantServiceReq_CreateBook) XXX_Size() int {
	return xxx_messageInfo_MerchantServiceReq_CreateBook.Size(m)
}
func (m *MerchantServiceReq_CreateBook) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantServiceReq_CreateBook.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantServiceReq_CreateBook proto.InternalMessageInfo

func (m *MerchantServiceReq_CreateBook) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *MerchantServiceReq_CreateBook) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MerchantServiceReq_CreateBook) GetReceiptId() string {
	if m != nil {
		return m.ReceiptId
	}
	return ""
}

type MerchantServiceReq_ReadOrder struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantServiceReq_ReadOrder) Reset()         { *m = MerchantServiceReq_ReadOrder{} }
func (m *MerchantServiceReq_ReadOrder) String() string { return proto.CompactTextString(m) }
func (*MerchantServiceReq_ReadOrder) ProtoMessage()    {}
func (*MerchantServiceReq_ReadOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12, 1}
}

func (m *MerchantServiceReq_ReadOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantServiceReq_ReadOrder.Unmarshal(m, b)
}
func (m *MerchantServiceReq_ReadOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantServiceReq_ReadOrder.Marshal(b, m, deterministic)
}
func (m *MerchantServiceReq_ReadOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantServiceReq_ReadOrder.Merge(m, src)
}
func (m *MerchantServiceReq_ReadOrder) XXX_Size() int {
	return xxx_messageInfo_MerchantServiceReq_ReadOrder.Size(m)
}
func (m *MerchantServiceReq_ReadOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantServiceReq_ReadOrder.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantServiceReq_ReadOrder proto.InternalMessageInfo

func (m *MerchantServiceReq_ReadOrder) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

type MerchantServiceReq_ListOrders struct {
	Symbol               string    `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side                 string    `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`
	Strategy             string    `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	State                string    `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	UserId               string    `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Order                SortOrder `protobuf:"varint,6,opt,name=order,proto3,enum=fox.atm.service.SortOrder" json:"order,omitempty"`
	Cursor               string    `protobuf:"bytes,7,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit                int64     `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MerchantServiceReq_ListOrders) Reset()         { *m = MerchantServiceReq_ListOrders{} }
func (m *MerchantServiceReq_ListOrders) String() string { return proto.CompactTextString(m) }
func (*MerchantServiceReq_ListOrders) ProtoMessage()    {}
func (*MerchantServiceReq_ListOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12, 2}
}

func (m *MerchantServiceReq_ListOrders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantServiceReq_ListOrders.Unmarshal(m, b)
}
func (m *MerchantServiceReq_ListOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantServiceReq_ListOrders.Marshal(b, m, deterministic)
}
func (m *MerchantServiceReq_ListOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantServiceReq_ListOrders.Merge(m, src)
}
func (m *MerchantServiceReq_ListOrders) XXX_Size() int {
	return xxx_messageInfo_MerchantServiceReq_ListOrders.Size(m)
}
func (m *MerchantServiceReq_ListOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantServiceReq_ListOrders.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantServiceReq_ListOrders proto.InternalMessageInfo

func (m *MerchantServiceReq_ListOrders) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *MerchantServiceReq_ListOrders) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *MerchantServiceReq_ListOrders) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *MerchantServiceReq_ListOrders) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *MerchantServiceReq_ListOrders) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MerchantServiceReq_ListOrders) GetOrder() SortOrder {
	if m != nil {
		return m.Order
	}
	return SortOrder_DESC
}

func (m *MerchantServiceReq_ListOrders) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *MerchantServiceReq_ListOrders) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type MerchantServiceReq_CancelOrder struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantServiceReq_CancelOrder) Reset()         { *m = MerchantServiceReq_CancelOrder{} }
func (m *MerchantServiceReq_CancelOrder) String() string { return proto.CompactTextString(m) }
func (*MerchantServiceReq_CancelOrder) ProtoMessage()    {}
func (*MerchantServiceReq_CancelOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12, 3}
}

func (m *MerchantServiceReq_CancelOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantServiceReq_CancelOrder.Unmarshal(m, b)
}
func (m *MerchantServiceReq_CancelOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantServiceReq_CancelOrder.Marshal(b, m, deterministic)
}
func (m *MerchantServiceReq_CancelOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantServiceReq_CancelOrder.Merge(m, src)
}
func (m *MerchantServiceReq_CancelOrder) XXX_Size() int {
	return xxx_messageInfo_MerchantServiceReq_CancelOrder.Size(m)
}
func (m *MerchantServiceReq_CancelOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantServiceReq_CancelOrder.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantServiceReq_CancelOrder proto.InternalMessageInfo

func (m *MerchantServiceReq_CancelOrder) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

type MerchantServiceReq_ListOrderReports struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Cursor               string   `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantServiceReq_ListOrderReports) Reset()         { *m = MerchantServiceReq_ListOrderReports{} }
func (m *MerchantServiceReq_ListOrderReports) String() string { return proto.CompactTextString(m) }
func (*MerchantServiceReq_ListOrderReports) ProtoMessage()    {}
func (*MerchantServiceReq_ListOrderReports) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12, 4}
}

func (m *MerchantServiceReq_ListOrderReports) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantServiceReq_ListOrderReports.Unmarshal(m, b)
}
func (m *MerchantServiceReq_ListOrderReports) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantServiceReq_ListOrderReports.Marshal(b, m, deterministic)
}
func (m *MerchantServiceReq_ListOrderReports) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantServiceReq_ListOrderReports.Merge(m, src)
}
func (m *MerchantServiceReq_ListOrderReports) XXX_Size() int {
	return xxx_messageInfo_MerchantServiceReq_ListOrderReports.Size(m)
}
func (m *MerchantServiceReq_ListOrderReports) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantServiceReq_ListOrderReports.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantServiceReq_ListOrderReports proto.InternalMessageInfo

func (m *MerchantServiceReq_ListOrderReports) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *MerchantServiceReq_ListOrderReports) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *MerchantServiceReq_ListOrderReports) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type MerchantServiceResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantServiceResp) Reset()         { *m = MerchantServiceResp{} }
func (m *MerchantServiceResp) String() string { return proto.CompactTextString(m) }
func (*MerchantServiceResp) ProtoMessage()    {}
func (*MerchantServiceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *MerchantServiceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantServiceResp.Unmarshal(m, b)
}
func (m *MerchantServiceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantServiceResp.Marshal(b, m, deterministic)
}
func (m *MerchantServiceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantServiceResp.Merge(m, src)
}
func (m *MerchantServiceResp) XXX_Size() int {
	return xxx_messageInfo_MerchantServiceResp.Size(m)
}
func (m *MerchantServiceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantServiceResp.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantServiceResp proto.InternalMessageInfo

type MerchantServiceResp_CancelOrder struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantServiceResp_CancelOrder) Reset()         { *m = MerchantServiceResp_CancelOrder{} }
func (m *MerchantServiceResp_CancelOrder) String() string { return proto.CompactTextString(m) }
func (*MerchantServiceResp_CancelOrder) ProtoMessage()    {}
func (*MerchantServiceResp_CancelOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13, 0}
}

func (m *MerchantServiceResp_CancelOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantServiceResp_CancelOrder.Unmarshal(m, b)
}
func (m *MerchantServiceResp_CancelOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantServiceResp_CancelOrder.Marshal(b, m, deterministic)
}
func (m *MerchantServiceResp_CancelOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantServiceResp_CancelOrder.Merge(m, src)
}
func (m *MerchantServiceResp_CancelOrder) XXX_Size() int {
	return xxx_messageInfo_MerchantServiceResp_CancelOrder.Size(m)
}
func (m *MerchantServiceResp_CancelOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantServiceResp_CancelOrder.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantServiceResp_CancelOrder proto.InternalMessageInfo

type MerchantServiceResp_ListOrders struct {
	Orders               []*Order    `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Pagination           *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MerchantServiceResp_ListOrders) Reset()         { *m = MerchantServiceResp_ListOrders{} }
func (m *MerchantServiceResp_ListOrders) String() string { return proto.CompactTextString(m) }
func (*MerchantServiceResp_ListOrders) ProtoMessage()    {}
func (*MerchantServiceResp_ListOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13, 1}
}

func (m *MerchantServiceResp_ListOrders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantServiceResp_ListOrders.Unmarshal(m, b)
}
func (m *MerchantServiceResp_ListOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantServiceResp_ListOrders.Marshal(b, m, deterministic)
}
func (m *MerchantServiceResp_ListOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantServiceResp_ListOrders.Merge(m, src)
}
func (m *MerchantServiceResp_ListOrders) XXX_Size() int {
	return xxx_messageInfo_MerchantServiceResp_ListOrders.Size(m)
}
func (m *MerchantServiceResp_ListOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantServiceResp_ListOrders.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantServiceResp_ListOrders proto.InternalMessageInfo

func (m *MerchantServiceResp_ListOrders) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *MerchantServiceResp_ListOrders) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type MerchantServiceResp_ListOrderReports struct {
	Reports              []*OrderReport `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	Pagination           *Pagination    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MerchantServiceResp_ListOrderReports) Reset()         { *m = MerchantServiceResp_ListOrderReports{} }
func (m *MerchantServiceResp_ListOrderReports) String() string { return proto.CompactTextString(m) }
func (*MerchantServiceResp_ListOrderReports) ProtoMessage()    {}
func (*MerchantServiceResp_ListOrderReports) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13, 2}
}

func (m *MerchantServiceResp_ListOrderReports) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantServiceResp_ListOrderReports.Unmarshal(m, b)
}
func (m *MerchantServiceResp_ListOrderReports) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantServiceResp_ListOrderReports.Marshal(b, m, deterministic)
}
func (m *MerchantServiceResp_ListOrderReports) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantServiceResp_ListOrderReports.Merge(m, src)
}
func (m *MerchantServiceResp_ListOrderReports) XXX_Size() int {
	return xxx_messageInfo_MerchantServiceResp_ListOrderReports.Size(m)
}
func (m *MerchantServiceResp_ListOrderReports) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantServiceResp_ListOrderReports.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantServiceResp_ListOrderReports proto.InternalMessageInfo

func (m *MerchantServiceResp_ListOrderReports) GetReports() []*OrderReport {
	if m != nil {
		return m.Reports
	}
	return nil
}

func (m *MerchantServiceResp_ListOrderReports) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterEnum("fox.atm.service.Side", Side_name, Side_value)
	proto.RegisterEnum("fox.atm.service.Strategy", Strategy_name, Strategy_value)
	proto.RegisterEnum("fox.atm.service.SortOrder", SortOrder_name, SortOrder_value)
	proto.RegisterEnum("fox.atm.service.Pair_State", Pair_State_name, Pair_State_value)
	proto.RegisterEnum("fox.atm.service.Book_State", Book_State_name, Book_State_value)
	proto.RegisterEnum("fox.atm.service.Order_State", Order_State_name, Order_State_value)
	proto.RegisterType((*Pagination)(nil), "fox.atm.service.Pagination")
	proto.RegisterType((*Depth)(nil), "fox.atm.service.Depth")
	proto.RegisterType((*Depth_Order)(nil), "fox.atm.service.Depth.Order")
	proto.RegisterType((*Asset)(nil), "fox.atm.service.Asset")
	proto.RegisterType((*Pair)(nil), "fox.atm.service.Pair")
	proto.RegisterType((*Book)(nil), "fox.atm.service.Book")
	proto.RegisterType((*Order)(nil), "fox.atm.service.Order")
	proto.RegisterType((*OrderReport)(nil), "fox.atm.service.OrderReport")
	proto.RegisterType((*User)(nil), "fox.atm.service.User")
	proto.RegisterType((*MarketServiceReq)(nil), "fox.atm.service.MarketServiceReq")
	proto.RegisterType((*MarketServiceReq_ListPairs)(nil), "fox.atm.service.MarketServiceReq.ListPairs")
	proto.RegisterType((*MarketServiceReq_ReadPair)(nil), "fox.atm.service.MarketServiceReq.ReadPair")
	proto.RegisterType((*MarketServiceReq_ReadDepth)(nil), "fox.atm.service.MarketServiceReq.ReadDepth")
	proto.RegisterType((*MarketServiceResp)(nil), "fox.atm.service.MarketServiceResp")
	proto.RegisterType((*MarketServiceResp_ListPairs)(nil), "fox.atm.service.MarketServiceResp.ListPairs")
	proto.RegisterType((*UserServiceReq)(nil), "fox.atm.service.UserServiceReq")
	proto.RegisterType((*UserServiceReq_Me)(nil), "fox.atm.service.UserServiceReq.Me")
	proto.RegisterType((*UserServiceReq_ReadOrder)(nil), "fox.atm.service.UserServiceReq.ReadOrder")
	proto.RegisterType((*UserServiceReq_ListOrders)(nil), "fox.atm.service.UserServiceReq.ListOrders")
	proto.RegisterType((*UserServiceReq_CancelOrder)(nil), "fox.atm.service.UserServiceReq.CancelOrder")
	proto.RegisterType((*UserServiceResp)(nil), "fox.atm.service.UserServiceResp")
	proto.RegisterType((*UserServiceResp_CancelOrder)(nil), "fox.atm.service.UserServiceResp.CancelOrder")
	proto.RegisterType((*UserServiceResp_ListOrders)(nil), "fox.atm.service.UserServiceResp.ListOrders")
	proto.RegisterType((*MerchantServiceReq)(nil), "fox.atm.service.MerchantServiceReq")
	proto.RegisterType((*MerchantServiceReq_CreateBook)(nil), "fox.atm.service.MerchantServiceReq.CreateBook")
	proto.RegisterType((*MerchantServiceReq_ReadOrder)(nil), "fox.atm.service.MerchantServiceReq.ReadOrder")
	proto.RegisterType((*MerchantServiceReq_ListOrders)(nil), "fox.atm.service.MerchantServiceReq.ListOrders")
	proto.RegisterType((*MerchantServiceReq_CancelOrder)(nil), "fox.atm.service.MerchantServiceReq.CancelOrder")
	proto.RegisterType((*MerchantServiceReq_ListOrderReports)(nil), "fox.atm.service.MerchantServiceReq.ListOrderReports")
	proto.RegisterType((*MerchantServiceResp)(nil), "fox.atm.service.MerchantServiceResp")
	proto.RegisterType((*MerchantServiceResp_CancelOrder)(nil), "fox.atm.service.MerchantServiceResp.CancelOrder")
	proto.RegisterType((*MerchantServiceResp_ListOrders)(nil), "fox.atm.service.MerchantServiceResp.ListOrders")
	proto.RegisterType((*MerchantServiceResp_ListOrderReports)(nil), "fox.atm.service.MerchantServiceResp.ListOrderReports")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 1766 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4b, 0x73, 0xdb, 0x5e,
	0x15, 0xff, 0x4b, 0x96, 0xfc, 0x38, 0x8e, 0x6d, 0xf5, 0xb6, 0xff, 0xa0, 0xaa, 0x8f, 0x04, 0x75,
	0x4a, 0xd3, 0xa4, 0x28, 0xc5, 0x50, 0x1e, 0xc3, 0x30, 0x4c, 0x92, 0xd2, 0x21, 0x4c, 0x53, 0x32,
	0x72, 0xd9, 0xc0, 0xc2, 0x73, 0x63, 0xdd, 0x38, 0x22, 0xb2, 0xe5, 0xea, 0xca, 0xc5, 0x59, 0xb1,
	0x60, 0xc1, 0x9e, 0x15, 0x33, 0xb0, 0x64, 0xc3, 0xf7, 0x60, 0xc3, 0x17, 0xe0, 0x0b, 0xb0, 0x64,
	0xc1, 0x0c, 0x1b, 0xb6, 0xcc, 0x7d, 0xc8, 0xba, 0xb2, 0xec, 0x38, 0x81, 0x0e, 0xd3, 0x55, 0x74,
	0xcf, 0xfd, 0xdd, 0x7b, 0xce, 0x3d, 0xe7, 0x77, 0x1e, 0x0e, 0xb4, 0x28, 0x49, 0x3e, 0x86, 0x03,
	0xe2, 0x4d, 0x92, 0x38, 0x8d, 0x51, 0xe7, 0x3c, 0x9e, 0x79, 0x38, 0x1d, 0x79, 0x52, 0xec, 0x6c,
	0x0d, 0xe3, 0x78, 0x18, 0x91, 0x7d, 0xbe, 0x7d, 0x36, 0x3d, 0xdf, 0x4f, 0xc3, 0x11, 0xa1, 0x29,
	0x1e, 0x4d, 0xc4, 0x09, 0xf7, 0xc7, 0x00, 0xa7, 0x78, 0x18, 0x8e, 0x71, 0x1a, 0xc6, 0x63, 0xb4,
	0x05, 0xcd, 0x31, 0x99, 0xa5, 0xfd, 0xc1, 0x34, 0xa1, 0x71, 0x62, 0x6b, 0xdb, 0xda, 0x4e, 0xc3,
	0x07, 0x26, 0x3a, 0xe2, 0x12, 0x74, 0x1f, 0xea, 0x17, 0x98, 0xf6, 0x99, 0xc4, 0xd6, 0xb7, 0xb5,
	0x9d, 0xba, 0x5f, 0xbb, 0xc0, 0xf4, 0x1d, 0x99, 0xa5, 0xee, 0xbf, 0x35, 0x30, 0x5f, 0x93, 0x49,
	0x7a, 0x81, 0x6c, 0xa8, 0x7d, 0x24, 0x09, 0x0d, 0xe3, 0xb1, 0xbc, 0x21, 0x5b, 0xa2, 0xef, 0x01,
	0x4c, 0x27, 0x01, 0x4e, 0x49, 0xd0, 0xc7, 0xe2, 0x82, 0x66, 0xd7, 0xf1, 0x84, 0x8d, 0x5e, 0x66,
	0xa3, 0xf7, 0x3e, 0xb3, 0xd1, 0x6f, 0x48, 0xf4, 0x41, 0x8a, 0x5e, 0x82, 0x81, 0xe9, 0x25, 0xb5,
	0x2b, 0xdb, 0x95, 0x9d, 0x66, 0xf7, 0xa1, 0xb7, 0xf0, 0x52, 0x8f, 0xab, 0xf6, 0x7e, 0x9a, 0x04,
	0x24, 0xf1, 0x39, 0x92, 0x9d, 0x38, 0x0b, 0x03, 0x6a, 0x1b, 0x37, 0x39, 0xc1, 0x90, 0xce, 0x2b,
	0x30, 0xf9, 0x12, 0xdd, 0x03, 0x73, 0x92, 0x84, 0x03, 0x22, 0xed, 0x17, 0x0b, 0xb4, 0x09, 0x55,
	0x3c, 0x8a, 0xa7, 0x63, 0x61, 0x79, 0xc3, 0x97, 0x2b, 0xf7, 0x4f, 0x1a, 0x98, 0x07, 0x94, 0x92,
	0x94, 0xb9, 0x07, 0xb3, 0x8f, 0x7e, 0x18, 0x64, 0x4f, 0xe7, 0xeb, 0xe3, 0x80, 0x1d, 0xa6, 0x57,
	0xa3, 0xb3, 0x38, 0xca, 0x0e, 0x8b, 0x15, 0x42, 0x60, 0x44, 0xf1, 0x30, 0xb6, 0x2b, 0x5c, 0xca,
	0xbf, 0x99, 0x6c, 0x8c, 0x47, 0xc4, 0x36, 0x84, 0x8c, 0x7d, 0xa3, 0x87, 0xd0, 0x98, 0x24, 0x64,
	0x10, 0x72, 0xb7, 0x9a, 0xdb, 0xda, 0x8e, 0xe9, 0xe7, 0x02, 0x64, 0x41, 0x65, 0x14, 0x8e, 0xed,
	0x2a, 0x3f, 0xc0, 0x3e, 0xb9, 0x04, 0xcf, 0xec, 0x9a, 0x94, 0xe0, 0x99, 0xfb, 0x3b, 0x03, 0x8c,
	0x53, 0x1c, 0x26, 0x8a, 0x29, 0x5a, 0xc1, 0x94, 0xa7, 0xd0, 0x0e, 0x42, 0x3a, 0x89, 0xf0, 0x55,
	0xbf, 0x60, 0x6a, 0x4b, 0x4a, 0x7b, 0x02, 0xe6, 0x40, 0x9d, 0xcc, 0x06, 0x17, 0x78, 0x3c, 0x24,
	0xd2, 0xea, 0xf9, 0x1a, 0x7d, 0x03, 0x4c, 0x9a, 0xe2, 0x54, 0x98, 0xde, 0xee, 0x3e, 0x28, 0x39,
	0x9d, 0x19, 0xe0, 0xf5, 0x18, 0xc4, 0x17, 0x48, 0xf4, 0x0c, 0x3a, 0xdc, 0xbd, 0xfd, 0xc5, 0xe7,
	0xb5, 0xb9, 0xf8, 0x74, 0xfe, 0xc6, 0xa7, 0xd0, 0x3e, 0xc3, 0x54, 0xc5, 0x55, 0x39, 0xae, 0xc5,
	0xa4, 0x39, 0xec, 0x19, 0x74, 0x3e, 0x4c, 0xe3, 0x54, 0xc5, 0xd5, 0xc4, 0x7d, 0x5c, 0x9c, 0x03,
	0x37, 0xa1, 0x2a, 0x5f, 0x51, 0x17, 0x6e, 0x90, 0x6f, 0x98, 0x07, 0xbf, 0xa1, 0x06, 0xff, 0x01,
	0xf3, 0x3f, 0x33, 0xf3, 0x6c, 0x7a, 0x65, 0x83, 0x78, 0x36, 0x17, 0x1c, 0x4e, 0xaf, 0xd0, 0x23,
	0x00, 0xb1, 0x49, 0x49, 0x14, 0xd9, 0x4d, 0xbe, 0x2b, 0xe0, 0x3d, 0x12, 0x45, 0xe8, 0x31, 0x00,
	0x4d, 0x13, 0x9c, 0x92, 0x61, 0x48, 0xa8, 0xbd, 0xb1, 0x5d, 0x61, 0x59, 0x95, 0x4b, 0xd0, 0x2e,
	0x18, 0xec, 0x0d, 0x76, 0x8b, 0x27, 0xc4, 0x66, 0xc9, 0x69, 0x9c, 0x5c, 0x3e, 0xc7, 0xa0, 0x17,
	0x60, 0xf2, 0x77, 0xd8, 0xed, 0x6b, 0xc1, 0x02, 0xe4, 0x6e, 0x81, 0xc9, 0x9d, 0x8d, 0x9a, 0x50,
	0x7b, 0x9f, 0xe0, 0x20, 0x1c, 0x0f, 0xad, 0x2f, 0x50, 0x03, 0xcc, 0xc3, 0x84, 0xe0, 0x4b, 0x4b,
	0x73, 0xff, 0x6a, 0x80, 0x71, 0x18, 0xc7, 0x97, 0xa8, 0x0d, 0xfa, 0x9c, 0xb4, 0x7a, 0x18, 0xb0,
	0x54, 0x1d, 0x24, 0xe4, 0x16, 0xa9, 0x2a, 0xd1, 0x07, 0x69, 0x4e, 0x82, 0xca, 0x0a, 0x12, 0x30,
	0x85, 0x45, 0x12, 0x6c, 0x41, 0x73, 0x44, 0x12, 0x16, 0x00, 0x9e, 0x3b, 0x82, 0xf8, 0x90, 0x89,
	0x8e, 0x03, 0xe6, 0xfe, 0xb3, 0x24, 0xbe, 0x24, 0x09, 0xdb, 0x36, 0x85, 0xfb, 0x85, 0xe0, 0x38,
	0x60, 0x69, 0x97, 0x26, 0x78, 0x40, 0xd8, 0x9e, 0x48, 0x81, 0x1a, 0x5f, 0x1f, 0x07, 0xe8, 0x2b,
	0x50, 0x9b, 0x52, 0x71, 0x4a, 0xa4, 0x42, 0x95, 0x2d, 0x8f, 0x03, 0x1e, 0x65, 0x7c, 0x45, 0x12,
	0x19, 0x7c, 0xb1, 0x60, 0x76, 0xd0, 0x31, 0x9e, 0xd0, 0x8b, 0x98, 0xdb, 0x21, 0x18, 0x00, 0x99,
	0xe8, 0x38, 0x60, 0x91, 0x4e, 0xc8, 0x80, 0x84, 0x13, 0xbe, 0x2f, 0x78, 0xd0, 0x90, 0x92, 0xe3,
	0x80, 0x65, 0xee, 0x88, 0x8c, 0x62, 0x49, 0x01, 0xfe, 0xcd, 0x34, 0x9d, 0x4f, 0xc7, 0x01, 0x0b,
	0x3c, 0xd7, 0xc4, 0x17, 0x9c, 0x32, 0x79, 0xa2, 0xb5, 0x24, 0x65, 0xe6, 0x49, 0xb6, 0x05, 0xcd,
	0xf3, 0x30, 0x8a, 0xb2, 0xfd, 0xb6, 0x30, 0x84, 0x89, 0x24, 0xe0, 0x15, 0xd4, 0x25, 0x83, 0xae,
	0xec, 0x0e, 0xf7, 0xf3, 0xfd, 0x92, 0x9f, 0x7b, 0x12, 0xe0, 0xcf, 0xa1, 0x39, 0xb9, 0x2d, 0x95,
	0xdc, 0x0e, 0xd4, 0x83, 0x90, 0x0e, 0x78, 0x6d, 0xbb, 0x23, 0x9c, 0x9b, 0xad, 0xdd, 0x1d, 0x85,
	0x42, 0xa7, 0x64, 0x2c, 0x29, 0x54, 0xe7, 0xb5, 0x24, 0xb0, 0x34, 0xf6, 0xf5, 0x3a, 0x1e, 0x13,
	0x4b, 0x77, 0xff, 0x52, 0xcd, 0xea, 0xe7, 0x27, 0x24, 0x53, 0xb1, 0x65, 0x54, 0x6e, 0xd3, 0x32,
	0x7e, 0x00, 0x1b, 0x03, 0x3c, 0x1e, 0x90, 0x28, 0x12, 0x87, 0x8d, 0xb5, 0x87, 0x9b, 0x73, 0xfc,
	0x41, 0xaa, 0x52, 0xc7, 0x2c, 0x50, 0x67, 0x81, 0xac, 0xd5, 0x12, 0x59, 0xbb, 0x59, 0x02, 0xd4,
	0x78, 0x60, 0xca, 0xad, 0x87, 0x7b, 0xa9, 0x98, 0x01, 0x45, 0x3e, 0xd4, 0xd7, 0xf0, 0xa1, 0x51,
	0xe2, 0x43, 0x5e, 0xd4, 0xa1, 0x50, 0xd4, 0x9f, 0x83, 0x41, 0xc3, 0x80, 0x70, 0x46, 0xb6, 0xbb,
	0x5f, 0x96, 0x39, 0x12, 0x06, 0xc4, 0xe7, 0x90, 0x02, 0xa5, 0x36, 0xfe, 0x0b, 0x4a, 0xb5, 0x56,
	0x51, 0xaa, 0x5d, 0xa4, 0x54, 0x9e, 0x11, 0x1d, 0x35, 0x23, 0xbe, 0x0a, 0x1b, 0xec, 0x3d, 0x24,
	0xe8, 0x8b, 0x4d, 0xc1, 0xd0, 0xa6, 0x90, 0xbd, 0xe1, 0x90, 0x27, 0xd0, 0x92, 0x10, 0xd9, 0x88,
	0x05, 0x59, 0xe5, 0xb9, 0x03, 0x2e, 0x43, 0x1e, 0xdc, 0x25, 0xb3, 0x34, 0xc1, 0xfd, 0x22, 0x14,
	0x71, 0xe8, 0x1d, 0xbe, 0xf5, 0x46, 0xc5, 0x3f, 0x02, 0x38, 0x27, 0x24, 0x83, 0xdd, 0x15, 0x9e,
	0x3f, 0x27, 0x44, 0x6e, 0x3f, 0x81, 0x16, 0xfe, 0x48, 0x12, 0x3c, 0x64, 0x1d, 0x85, 0x3d, 0xf3,
	0x9e, 0xd0, 0x29, 0x85, 0xa7, 0x4c, 0xe6, 0xfe, 0x64, 0x69, 0x9d, 0x05, 0xa8, 0x0a, 0x4d, 0x96,
	0x86, 0x5a, 0xd0, 0x38, 0xca, 0xc8, 0x65, 0xe9, 0x68, 0x03, 0xea, 0x3e, 0xf9, 0x25, 0x19, 0xa4,
	0x24, 0xb0, 0x2a, 0xfc, 0x54, 0x38, 0x22, 0xf1, 0x34, 0xb5, 0x0c, 0xf7, 0x5f, 0x3a, 0x34, 0xc5,
	0x54, 0x42, 0x26, 0x71, 0x92, 0x7e, 0xca, 0x64, 0x42, 0x60, 0x04, 0x59, 0x61, 0x6e, 0xf8, 0xfc,
	0x5b, 0xa5, 0xb9, 0x71, 0x1d, 0xcd, 0xcd, 0x12, 0xcd, 0x73, 0xca, 0x55, 0x17, 0x47, 0x1a, 0x4e,
	0x39, 0x51, 0x70, 0x05, 0xb7, 0x4a, 0x91, 0xab, 0x2f, 0x89, 0xdc, 0x33, 0xe8, 0xc4, 0x67, 0x29,
	0x0e, 0xc7, 0x39, 0x4c, 0x10, 0xbd, 0x9d, 0x89, 0x97, 0x86, 0x0c, 0x16, 0x43, 0xf6, 0x00, 0x1a,
	0x7c, 0x9b, 0x75, 0x42, 0x59, 0x8a, 0xeb, 0x6c, 0x97, 0xcf, 0x68, 0xf7, 0xc0, 0x14, 0xac, 0xdc,
	0xe0, 0x53, 0x81, 0x58, 0xb8, 0xbf, 0x00, 0xe3, 0x67, 0x74, 0x49, 0xe5, 0xca, 0x46, 0x31, 0x5d,
	0x19, 0xc5, 0x10, 0x18, 0x49, 0x1c, 0xcd, 0xbd, 0xc8, 0xbe, 0x8b, 0xfd, 0xc9, 0x28, 0xf6, 0x27,
	0xf7, 0x02, 0xac, 0x13, 0x9c, 0x5c, 0x92, 0xb4, 0x27, 0xb2, 0xc8, 0x27, 0x1f, 0x9c, 0x26, 0x34,
	0xde, 0x86, 0x34, 0x65, 0xf3, 0x10, 0x75, 0x5c, 0xc6, 0x06, 0x1c, 0x5c, 0x37, 0x9d, 0x39, 0x4f,
	0xa0, 0xc1, 0x30, 0x62, 0xc4, 0x5e, 0x01, 0x72, 0x4f, 0xe0, 0xce, 0x82, 0x26, 0x3a, 0x71, 0xbe,
	0xab, 0xa8, 0x42, 0x7b, 0xac, 0xef, 0x85, 0x09, 0xb5, 0x35, 0x3e, 0x16, 0x7f, 0xb9, 0x74, 0x42,
	0xf3, 0x05, 0xc6, 0xfd, 0x9b, 0x0e, 0x6d, 0xe6, 0x16, 0xc5, 0x6e, 0x03, 0xf4, 0x13, 0xe2, 0x7c,
	0x4d, 0x18, 0x23, 0xaa, 0xbd, 0xda, 0x7e, 0xb5, 0x42, 0xfb, 0x75, 0xfe, 0xa1, 0x01, 0x30, 0xdd,
	0x1c, 0x48, 0x57, 0x4e, 0x9e, 0x19, 0x63, 0x74, 0x85, 0x31, 0x8e, 0x52, 0x8d, 0xe4, 0x98, 0xa9,
	0x96, 0x9c, 0x7c, 0xcc, 0x6c, 0xac, 0x18, 0x22, 0xca, 0x84, 0x7d, 0x09, 0x66, 0xcc, 0x0c, 0xe1,
	0x7c, 0x6d, 0x77, 0x9d, 0x72, 0x75, 0x8b, 0x13, 0x61, 0xaa, 0x2f, 0x80, 0x7c, 0x46, 0x14, 0xbf,
	0x85, 0xe4, 0xf4, 0x20, 0x56, 0xcc, 0x80, 0x28, 0x1c, 0x85, 0x82, 0xc6, 0x15, 0x5f, 0x2c, 0x9c,
	0x1d, 0x68, 0x8a, 0x1c, 0x5f, 0xe7, 0x17, 0xf7, 0x0f, 0x1a, 0x74, 0x0a, 0x8e, 0xa5, 0x13, 0xa7,
	0x55, 0x38, 0xed, 0x5c, 0x15, 0x3c, 0xe7, 0x41, 0x95, 0x5b, 0x94, 0xc5, 0x6d, 0x73, 0x79, 0x4f,
	0xf1, 0x25, 0x0a, 0x7d, 0x9f, 0xb5, 0x93, 0xec, 0x77, 0x9d, 0x2c, 0x12, 0xcb, 0xa6, 0xf1, 0x0c,
	0xe2, 0x2b, 0x70, 0xf7, 0x37, 0x06, 0xa0, 0x13, 0xe9, 0x36, 0x25, 0xf4, 0x7d, 0x80, 0x23, 0x5e,
	0x4a, 0xf8, 0xc0, 0xb8, 0xfa, 0x75, 0x6a, 0x49, 0xd1, 0x0b, 0x25, 0xa5, 0x38, 0x3d, 0x55, 0x16,
	0xa6, 0xa7, 0x1b, 0xb3, 0xea, 0xef, 0xff, 0x4f, 0x56, 0xad, 0x1c, 0x03, 0x3e, 0x1b, 0x36, 0x39,
	0xef, 0xc1, 0x9a, 0xbb, 0x43, 0x34, 0x0d, 0x3a, 0x2f, 0xf5, 0x9a, 0x52, 0xea, 0x73, 0xfd, 0xfa,
	0x72, 0xfd, 0x15, 0x45, 0xbf, 0xfb, 0x67, 0x1d, 0xee, 0x96, 0x58, 0xf0, 0x39, 0xf1, 0xd4, 0xf9,
	0xad, 0xb6, 0xe4, 0xe1, 0xdf, 0x86, 0x5a, 0x22, 0x3e, 0xa5, 0x09, 0x2b, 0xc6, 0x2f, 0x81, 0xf7,
	0x33, 0xf0, 0xff, 0x64, 0xc9, 0xae, 0x0d, 0x06, 0x1b, 0xa4, 0x50, 0x0d, 0x2a, 0x07, 0xf4, 0xd2,
	0xfa, 0x82, 0x7d, 0x1c, 0xb2, 0xf1, 0x78, 0xf7, 0x3b, 0x50, 0xcf, 0x66, 0x26, 0x36, 0x0f, 0x88,
	0xea, 0x2c, 0x7e, 0x83, 0xbd, 0x65, 0x6e, 0xb6, 0x34, 0x3e, 0x26, 0xc4, 0x51, 0x14, 0xff, 0xca,
	0xd2, 0xd9, 0x34, 0xfd, 0x26, 0x22, 0x33, 0xab, 0xb2, 0xfb, 0x18, 0x1a, 0x73, 0x02, 0xf1, 0x21,
	0xfb, 0x47, 0xbd, 0x23, 0x71, 0xf1, 0x41, 0xef, 0xc8, 0xd2, 0xba, 0xbf, 0xd7, 0xa1, 0x55, 0xa8,
	0xf5, 0xe8, 0xbc, 0x50, 0xe7, 0x4b, 0xa6, 0x2f, 0xb6, 0x20, 0x2f, 0xef, 0x3f, 0x2f, 0xd6, 0x81,
	0xe9, 0x24, 0x47, 0xa3, 0x13, 0xa5, 0x5b, 0xed, 0xae, 0x57, 0x93, 0x61, 0x9d, 0xe5, 0xbd, 0x06,
	0x9d, 0xaa, 0x8d, 0x6d, 0xef, 0x66, 0xf7, 0x71, 0xb0, 0xb3, 0xb9, 0xfc, 0x7f, 0x3a, 0xdd, 0x7f,
	0xea, 0xd0, 0x54, 0xaa, 0x2b, 0xfa, 0x21, 0xeb, 0x59, 0xc8, 0x2d, 0xa1, 0x8b, 0xad, 0xcd, 0x3b,
	0x21, 0x4b, 0x4c, 0xe4, 0x53, 0xc1, 0x3b, 0xb5, 0x30, 0x3d, 0x5f, 0x77, 0xcf, 0x1c, 0xea, 0xac,
	0x60, 0x3f, 0x22, 0x85, 0x9c, 0xd9, 0x5d, 0x77, 0x61, 0x8e, 0x75, 0xf6, 0xae, 0xc7, 0xca, 0x38,
	0xc9, 0x8b, 0x2f, 0x8a, 0x15, 0x64, 0x6f, 0x9d, 0x1e, 0x35, 0xad, 0x5f, 0xac, 0x55, 0xa4, 0xa0,
	0xbb, 0x7f, 0x34, 0xa0, 0xb3, 0x50, 0x2b, 0x50, 0xaf, 0xd0, 0x2e, 0xbc, 0x72, 0x60, 0x4b, 0x1d,
	0xc6, 0xcb, 0xf1, 0x4b, 0x22, 0xc1, 0xaf, 0xf1, 0xd5, 0x48, 0x7c, 0xfd, 0x26, 0x77, 0xae, 0x8f,
	0xc6, 0xa8, 0x58, 0xc1, 0x6e, 0x72, 0xa9, 0x12, 0x91, 0xfd, 0xf5, 0xf8, 0x62, 0x54, 0x7e, 0xbd,
	0xa4, 0x68, 0x7d, 0xeb, 0x56, 0x4a, 0xe5, 0x29, 0xe7, 0xd5, 0xed, 0x54, 0x67, 0xca, 0x26, 0x45,
	0x5a, 0xec, 0xdf, 0x28, 0x32, 0x0a, 0x35, 0x5e, 0xde, 0x48, 0xad, 0x72, 0xe2, 0xb0, 0xf6, 0x73,
	0x53, 0xfc, 0x30, 0xa9, 0xf2, 0x3f, 0xdf, 0xfc, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xbb,
	0xc1, 0x5a, 0xb8, 0x16, 0x00, 0x00,
}
